"""Add position field to Milestone

Revision ID: 152eda188aa8
Revises: 6d4610294a07
Create Date: 2024-10-16 13:16:20.266070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '152eda188aa8'
down_revision: Union[str, None] = '6d4610294a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('position', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_milestone_position'), 'milestone', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_milestone_position'), table_name='milestone')
    op.drop_column('milestone', 'position')
    # ### end Alembic commands ###
