"""Add due_date to milestone

Revision ID: c91a81153147
Revises: 9cf8da084ecb
Create Date: 2024-09-18 15:20:48.964516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c91a81153147'
down_revision: Union[str, None] = '9cf8da084ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('due_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestone', 'due_date')
    # ### end Alembic commands ###
