"""Update model

Revision ID: cf948bdb11ff
Revises: c86ddf6cd9d0
Create Date: 2024-09-23 23:54:25.676617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf948bdb11ff'
down_revision: Union[str, None] = 'c86ddf6cd9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtask', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('subtask', 'descrpition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtask', sa.Column('descrpition', sa.VARCHAR(), nullable=False))
    op.drop_column('subtask', 'description')
    # ### end Alembic commands ###
