"""change_google_user_id_to_string_in_googlecalendar_table

Revision ID: d23314545776
Revises: 338f3a74f9df
Create Date: 2025-06-05 02:32:16.805233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd23314545776'
down_revision: Union[str, None] = '338f3a74f9df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   with op.batch_alter_table('googlecalendar', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
        Existing_type=sa.VARCHAR(), 
        Type_=sa.DateTime(), 
        Existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   with op.batch_alter_table('googlecalendar', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
        Existing_type=sa.DateTime(),
        Type_=sa.VARCHAR(), 
        Existing_nullable=True)
    # ### end Alembic commands ###
